refactored stylesheet
T-NAVe/SAL pull request #5
Opened 2023-12-06 16:54 UTC by TimeIsOnMySide

2023-12-06 16:55 UTC, TimeIsOnMySide commented
closes #3

2023-12-11 18:57 UTC, T-NAVe requested changes
Hi! Thx for collaborating to this project.
So a few things, changes break styling:
![image](https://github.com/T-NAVe/SAL/assets/65693205/8151a5cf-848e-4eea-acf4-125eb55d64a4)
This is how is supposed to look:
![image](https://github.com/T-NAVe/SAL/assets/65693205/a1dd644b-cbf1-4149-abc4-88a515dc1add)

Another thing, tabsize of your changes is 4, it shjould be 2 [check the readme](https://github.com/T-NAVe/SAL#code-style). Even tho I do prefer tabsize of 2, having it changed in a PR makes it a lot harder to check actual changes, since I have have to search line by line on what has been changes. This is clear when checking the diff:
![image](https://github.com/T-NAVe/SAL/assets/65693205/39ed5d2a-6f78-4bae-9de7-31d63dd58fa8)

I'll await for the requested changes. Thx again for contributing 😁.

2023-12-11 23:53 UTC, TimeIsOnMySide commented
Thank you so much for the feedback! I will work on this and correct the errors

2023-12-12 01:39 UTC, TimeIsOnMySide commented
The newest commit addresses all your comments. Let me know if I missed anything.

2023-12-14 15:46 UTC, T-NAVe commented
Sorry for the delay I've been busy at work, I'll check your PR today pinky promise, thx!

2023-12-15 07:02 UTC, T-NAVe requested changes
Almost there!

This is the current result of the spreadsheet refactor
![image](https://github.com/T-NAVe/SAL/assets/65693205/ef4e5bef-7c71-436b-83b9-370f08bf2d42)
![image](https://github.com/T-NAVe/SAL/assets/65693205/a9b86e1f-db55-42db-8603-7662ca3710d6)

This is the expected result:
![image](https://github.com/T-NAVe/SAL/assets/65693205/f021d037-56b1-42f7-8493-43fab9663c35)
![image](https://github.com/T-NAVe/SAL/assets/65693205/daf7ed69-157d-4081-902a-e97a5c8b21cd)

Also I made you this to consider as an improvement I'll leave it up to you 😉
[Link](https://codi.link/PGgxPg0KICBFeGFtcGxlIGdyb3VwZWQgZGV0YWlscw0KPC9oMT4NCjxwPg0KICBUaGUgZGV0YWlscyBlbGVtZW50IGNhbiBiZTxzdHJvbmc+Imdyb3VwZWQiPC9zdHJvbmc+IHVzaW5nIHRoZSBhdHRyaWJ1dGUgPGNvZGU+bmFtZTwvY29kZT4NCjwvcD4NCjxkaXY+DQogIDxoMj5XaXRob3V0IGF0dHJpYnV0ZSBuYW1lPC9oMj4NCiAgPGRldGFpbHM+DQogICAgPHN1bW1hcnk+RXhhbXBsZSAxPC9zdW1tYXJ5Pg0KICAgIDxkaXY+IkxvcmVtIGlwc3VtIGRvbG9yIHNpdCBhbWV0LCBjb25zZWN0ZXR1ciBhZGlwaXNjaW5nIGVsaXQsIHNlZCBkbyBlaXVzbW9kIHRlbXBvciBpbmNpZGlkdW50IHV0IGxhYm9yZSBldCBkb2xvcmUgbWFnbmEgYWxpcXVhLiBVdCBlbmltIGFkIG1pbmltIHZlbmlhbSwgcXVpcyBub3N0cnVkIGV4ZXJjaXRhdGlvbiB1bGxhbWNvIGxhYm9yaXMgbmlzaSB1dCBhbGlxdWlwIGV4IGVhIGNvbW1vZG8gY29uc2VxdWF0LiBEdWlzIGF1dGUgaXJ1cmUgZG9sb3IgaW4gcmVwcmVoZW5kZXJpdCBpbiB2b2x1cHRhdGUgdmVsaXQgZXNzZSBjaWxsdW0gZG9sb3JlIGV1IGZ1Z2lhdCBudWxsYSBwYXJpYXR1ci4gRXhjZXB0ZXVyIHNpbnQgb2NjYWVjYXQgY3VwaWRhdGF0IG5vbiBwcm9pZGVudCwgc3VudCBpbiBjdWxwYSBxdWkgb2ZmaWNpYSBkZXNlcnVudCBtb2xsaXQgYW5pbSBpZCBlc3QgbGFib3J1bS4NCiAgICA8L2Rpdj4NCiAgPC9kZXRhaWxzPg0KICA8ZGV0YWlscz4NCiAgICA8c3VtbWFyeT5FeGFtcGxlIDI8L3N1bW1hcnk+DQogICAgPGRpdj4iTG9yZW0gaXBzdW0gZG9sb3Igc2l0IGFtZXQsIGNvbnNlY3RldHVyIGFkaXBpc2NpbmcgZWxpdCwgc2VkIGRvIGVpdXNtb2QgdGVtcG9yIGluY2lkaWR1bnQgdXQgbGFib3JlIGV0IGRvbG9yZSBtYWduYSBhbGlxdWEuIFV0IGVuaW0gYWQgbWluaW0gdmVuaWFtLCBxdWlzIG5vc3RydWQgZXhlcmNpdGF0aW9uIHVsbGFtY28gbGFib3JpcyBuaXNpIHV0IGFsaXF1aXAgZXggZWEgY29tbW9kbyBjb25zZXF1YXQuIER1aXMgYXV0ZSBpcnVyZSBkb2xvciBpbiByZXByZWhlbmRlcml0IGluIHZvbHVwdGF0ZSB2ZWxpdCBlc3NlIGNpbGx1bSBkb2xvcmUgZXUgZnVnaWF0IG51bGxhIHBhcmlhdHVyLiBFeGNlcHRldXIgc2ludCBvY2NhZWNhdCBjdXBpZGF0YXQgbm9uIHByb2lkZW50LCBzdW50IGluIGN1bHBhIHF1aSBvZmZpY2lhIGRlc2VydW50IG1vbGxpdCBhbmltIGlkIGVzdCBsYWJvcnVtLg0KICAgIDwvZGl2Pg0KICA8L2RldGFpbHM+DQogIDxkZXRhaWxzPg0KICAgIDxzdW1tYXJ5PkV4YW1wbGUgMzwvc3VtbWFyeT4NCiAgICA8ZGl2PiJMb3JlbSBpcHN1bSBkb2xvciBzaXQgYW1ldCwgY29uc2VjdGV0dXIgYWRpcGlzY2luZyBlbGl0LCBzZWQgZG8gZWl1c21vZCB0ZW1wb3IgaW5jaWRpZHVudCB1dCBsYWJvcmUgZXQgZG9sb3JlIG1hZ25hIGFsaXF1YS4gVXQgZW5pbSBhZCBtaW5pbSB2ZW5pYW0sIHF1aXMgbm9zdHJ1ZCBleGVyY2l0YXRpb24gdWxsYW1jbyBsYWJvcmlzIG5pc2kgdXQgYWxpcXVpcCBleCBlYSBjb21tb2RvIGNvbnNlcXVhdC4gRHVpcyBhdXRlIGlydXJlIGRvbG9yIGluIHJlcHJlaGVuZGVyaXQgaW4gdm9sdXB0YXRlIHZlbGl0IGVzc2UgY2lsbHVtIGRvbG9yZSBldSBmdWdpYXQgbnVsbGEgcGFyaWF0dXIuIEV4Y2VwdGV1ciBzaW50IG9jY2FlY2F0IGN1cGlkYXRhdCBub24gcHJvaWRlbnQsIHN1bnQgaW4gY3VscGEgcXVpIG9mZmljaWEgZGVzZXJ1bnQgbW9sbGl0IGFuaW0gaWQgZXN0IGxhYm9ydW0uDQogICAgPC9kaXY+DQogIDwvZGV0YWlscz4NCjwvZGl2Pg0KPGJyPg0KPGRpdj4NCiAgPGgyPldpdGggYXR0cmlidXRlIG5hbWU8L2gyPg0KICA8ZGV0YWlscyBuYW1lPSJqb2luZWQiIG9wZW4+DQogICAgPHN1bW1hcnk+RXhhbXBsZSAxPC9zdW1tYXJ5Pg0KICAgIDxkaXY+IkxvcmVtIGlwc3VtIGRvbG9yIHNpdCBhbWV0LCBjb25zZWN0ZXR1ciBhZGlwaXNjaW5nIGVsaXQsIHNlZCBkbyBlaXVzbW9kIHRlbXBvciBpbmNpZGlkdW50IHV0IGxhYm9yZSBldCBkb2xvcmUgbWFnbmEgYWxpcXVhLiBVdCBlbmltIGFkIG1pbmltIHZlbmlhbSwgcXVpcyBub3N0cnVkIGV4ZXJjaXRhdGlvbiB1bGxhbWNvIGxhYm9yaXMgbmlzaSB1dCBhbGlxdWlwIGV4IGVhIGNvbW1vZG8gY29uc2VxdWF0LiBEdWlzIGF1dGUgaXJ1cmUgZG9sb3IgaW4gcmVwcmVoZW5kZXJpdCBpbiB2b2x1cHRhdGUgdmVsaXQgZXNzZSBjaWxsdW0gZG9sb3JlIGV1IGZ1Z2lhdCBudWxsYSBwYXJpYXR1ci4gRXhjZXB0ZXVyIHNpbnQgb2NjYWVjYXQgY3VwaWRhdGF0IG5vbiBwcm9pZGVudCwgc3VudCBpbiBjdWxwYSBxdWkgb2ZmaWNpYSBkZXNlcnVudCBtb2xsaXQgYW5pbSBpZCBlc3QgbGFib3J1bS4NCiAgICA8L2Rpdj4NCiAgPC9kZXRhaWxzPg0KICA8ZGV0YWlscyBuYW1lPSJqb2luZWQiPg0KICAgIDxzdW1tYXJ5PkV4YW1wbGUgMjwvc3VtbWFyeT4NCiAgICA8ZGl2PiJMb3JlbSBpcHN1bSBkb2xvciBzaXQgYW1ldCwgY29uc2VjdGV0dXIgYWRpcGlzY2luZyBlbGl0LCBzZWQgZG8gZWl1c21vZCB0ZW1wb3IgaW5jaWRpZHVudCB1dCBsYWJvcmUgZXQgZG9sb3JlIG1hZ25hIGFsaXF1YS4gVXQgZW5pbSBhZCBtaW5pbSB2ZW5pYW0sIHF1aXMgbm9zdHJ1ZCBleGVyY2l0YXRpb24gdWxsYW1jbyBsYWJvcmlzIG5pc2kgdXQgYWxpcXVpcCBleCBlYSBjb21tb2RvIGNvbnNlcXVhdC4gRHVpcyBhdXRlIGlydXJlIGRvbG9yIGluIHJlcHJlaGVuZGVyaXQgaW4gdm9sdXB0YXRlIHZlbGl0IGVzc2UgY2lsbHVtIGRvbG9yZSBldSBmdWdpYXQgbnVsbGEgcGFyaWF0dXIuIEV4Y2VwdGV1ciBzaW50IG9jY2FlY2F0IGN1cGlkYXRhdCBub24gcHJvaWRlbnQsIHN1bnQgaW4gY3VscGEgcXVpIG9mZmljaWEgZGVzZXJ1bnQgbW9sbGl0IGFuaW0gaWQgZXN0IGxhYm9ydW0uDQogICAgPC9kaXY+DQogIDwvZGV0YWlscz4NCiAgPGRldGFpbHMgbmFtZT0iam9pbmVkIj4NCiAgICA8c3VtbWFyeT5FeGFtcGxlIDM8L3N1bW1hcnk+DQogICAgPGRpdj4iTG9yZW0gaXBzdW0gZG9sb3Igc2l0IGFtZXQsIGNvbnNlY3RldHVyIGFkaXBpc2NpbmcgZWxpdCwgc2VkIGRvIGVpdXNtb2QgdGVtcG9yIGluY2lkaWR1bnQgdXQgbGFib3JlIGV0IGRvbG9yZSBtYWduYSBhbGlxdWEuIFV0IGVuaW0gYWQgbWluaW0gdmVuaWFtLCBxdWlzIG5vc3RydWQgZXhlcmNpdGF0aW9uIHVsbGFtY28gbGFib3JpcyBuaXNpIHV0IGFsaXF1aXAgZXggZWEgY29tbW9kbyBjb25zZXF1YXQuIER1aXMgYXV0ZSBpcnVyZSBkb2xvciBpbiByZXByZWhlbmRlcml0IGluIHZvbHVwdGF0ZSB2ZWxpdCBlc3NlIGNpbGx1bSBkb2xvcmUgZXUgZnVnaWF0IG51bGxhIHBhcmlhdHVyLiBFeGNlcHRldXIgc2ludCBvY2NhZWNhdCBjdXBpZGF0YXQgbm9uIHByb2lkZW50LCBzdW50IGluIGN1bHBhIHF1aSBvZmZpY2lhIGRlc2VydW50IG1vbGxpdCBhbmltIGlkIGVzdCBsYWJvcnVtLg0KICAgIDwvZGl2Pg0KICA8L2RldGFpbHM+DQo8L2Rpdj4=%7CaHRtbCB7DQogIGZvbnQtZmFtaWx5OiBzYW5zLXNlcmlmOw0KfQ==%7CDQo=)

Tho generally speaking improvements should be added separately, but in this case I don't have a problem with it. In short, a refactor should not change the output.

If you have any doubts let me know, thx!

2023-12-15 07:02 UTC, T-NAVe commented on src/popup.css
> +.item_bar_onoff {
.item__bar__onoff lost gap wich is why we have a diff in the button.
![image](https://github.com/T-NAVe/SAL/assets/65693205/8bad5bdb-4927-41f9-b0a6-7dfb0a75edd6)

2023-12-15 07:02 UTC, T-NAVe commented on src/popup.css
> +  --font-size-base: 18px;
Right, this font-size we had here was just to set the "inital" value of our font size, so, since we are working in rem, we can adjust every variable at once since rem refers to root element. Is more common to see this applied more like this:

```css
html {
font-size: 18px
}

/*  or having this config into consideration */

html {
font-size: var(--font-size-base)
}
```

Putting it on the :root also works fine, but some may consider it a bad practice, don't ask me why.

2023-12-15 07:02 UTC, T-NAVe commented on src/popup.css
> -.module__smalldescription {
This was being used in the comment at the end of the extension, that's why we now see it bigger

2023-12-15 07:02 UTC, T-NAVe commented on src/popup.css
> +  margin-bottom: 6px;
So separating elements by having margin in every one may be fine in an project small as this one, in practice item separation should be given by the containers, meaby by a space between, perhaps with a gap, something like that. The problem on having margins by each element is that evaluating wich one is the one making the separation can get painful real quick 😂.

2023-12-17 19:44 UTC, TimeIsOnMySide commented
@T-NAVe Thank you for all your notes! Ive had a busy weekend but I will definitely work on this throughout the week. The next commit will fix all the inconsistencies.

2025-01-25 15:05 UTC, closed without merging